# Re-create autogenerated client code from OpenAPI spec
clients:
	kiota generate -l python -d http://ap-management:5000/openapi.json -o generated/ap_management -c ApManagementClient
	kiota generate -l python -d http://ap-executor:5000/openapi.json -o generated/ap_executor -c ApExecutorClient